service:
  type: LoadBalancer

securityContext:
  fsGroup: 1000

containerSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: true     # must be true to satisfy Kyverno
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

initSysctl:
  enabled: false                   # disable privileged sysctls

initFs:
  enabled: false                   # disable writes during init

postgresql:
  enabled: true
  auth:
    postgresPassword: sonar123
  primary:
    containerSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "800m"
    memory: "2Gi"
