service:
  type: LoadBalancer

securityContext:
  fsGroup: 1000

containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  # Keep readOnlyRootFilesystem: false to prevent init-fs crashes
  readOnlyRootFilesystem: false
  seccompProfile:
    type: RuntimeDefault

initContainers:
  securityContext:
    seccompProfile:
      type: RuntimeDefault

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "800m"
    memory: "2Gi"

postgresql:
  enabled: true
  auth:
    postgresPassword: "sonar123"
  primary:
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"
    containerSecurityContext:
      allowPrivilegeEscalation: true
      runAsUser: 0
      runAsGroup: 0
