apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privilege-escalation
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: check-priv-esc
      match:
        resources:
          kinds: ["Pod"]
      validate:
        message: "Privilege escalation is disallowed"
        pattern:
          spec:
            containers:
              - name: "*"
                securityContext:
                  allowPrivilegeEscalation: false
