apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-readonly-rootfs
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: require-read-only-root-fs
      match:
        resources:
          kinds: ["Pod"]
      exclude:
        resources:
          namespaces:
            - sonarqube
          names:
            - sonarqube-postgresql
      validate:
        message: "Root filesystem must be read-only"
        pattern:
          spec:
            containers:
              - name: "*"
                securityContext:
                  readOnlyRootFilesystem: true
