apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
  annotations:
    policies.kyverno.io/title: Require Resource Limits
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      CPU and memory limits must be set for all containers.
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: check-resource-limits
      match:
        any:
        - resources:
            kinds:
            - Pod
      exclude:
        any:
        - resources:
            kinds:
            - Pod
            namespaces:
            - kube-system
            - argocd
            - jenkins  # Added to exclude Jenkins namespace
            - sonarqube
      validate:
        message: "CPU and memory limits must be set"
        pattern:
          spec:
            containers:
            - name: "*"
              resources:
                limits:
                  memory: "?*"
                  cpu: "?*"